= Apællo Documentation
Luna Kilborn <leland.kilborn@hotmail.com>
:description: The official documentation for the Apællo Language
:stem: latexmath
:toc:

Apællo (pronounced uh - PIE - low) is a programming language based on Forth that adds first class functions, lists, and removes those unnecessary parser words. The original Forth language, designed in the 1970's was in wide use for home computers and maintains a significant pressence in embedded applications, due to the small size of the interpreter required to run it and the comfortability of low-level programming with it. Forth has been used everywhere, on people's home computers acting as a  pocket calculator, to teaching people about programming and computer science, to taking spacecraft to other planets and beyond. Forth is an amazing language, but that doesn't mean it can't be improved, which is what Apællo sets out to do.

== Words

The input is divided into lines, which are evaluated top to bottom, and further
into words that are separated by spaces. If the line is determined to be a code
line (more about other line types later) then the words in it are executed left
to right. First, a word is assumed to be the opening or closing of a list. If it
is not, then it is assumed to be a number. If it is not a number, then it is
assumed to be the creation of a constant or variable. If it is not this either,
then it is looked up in the dictionary. As this is the final step, if the word
remains unidentified, then an error is thrown to the user telling them that the
interpreter cannot find the word.

=== Lists

One of the primary additions over the original Forth that Apællo makes. They can
contain other lists, numbers, or words. Lists are started by a `[` word, and are
ended by `]`. Lists must be ended on the same line that they are started. The
words between the brackets are what is put into the list. Do note that because
the bracket symbols are their own words, they must be followed by a space. For
example, `[1` and `1]` will be considered as the single words `[1` and `1]`, and 
you must instead write `[ 1` and `1 ]` in order for it to be correctly processed
as a list. When the interpreter encounters a list, it will add it to memory and
push the identifier onto the top of the stack. However, if the list is contained
inside another list, then after being added to memory the list will instead be
replaced with a word containing the identifier of the list. When the list is run
this will create the same effect as if it was a top level list due to the 
behavior of number words, but this will be discussed more later.

NOTE: The identifier that is pushed to the stack is _not_ the memory location of
      the list, but rather the internal identifier number that is assigned to
      everything stored in the program's memory. This will be discussed later.

=== Numbers

Numbers can either be signed longs or double precision floats. If the number
contains a decimal, such as in `2.5` or `5.0`, then it will be stored as a 
float. However, if the number does not contain a decimal point, such as in `2`
or `5`, it will be stored as an integer. By default numbers are interpreted as a
decimal, but can instead be interpreted as a binary number if preceded by a `B`,
as an octal number if preceded by a `O`, and as a hex number if preceded by an
`X`. Because Apællo serves to free you from restrictions, unlike other languages
in which only integers can be in a non-decimal base, Apællo allows floats as
well to be written in non-decimal bases, such as in `X1B.B3F`.

=== Variables and Constants

One of the more important features of Forth is its ability to define variables
and constants. Variables store a mutable value who's _memory address_ is pushed 
to the top of the stack by executing the variable's name as a word. Constants 
store an immutable value who's _value_ is pushed to the top of the stack by 
executing the constant's name as a word. In Apællo they function similarly. In
normal practice the only difference will be that instead of pushing a memory
address to the stack it will push the _identifier_ to the top of the stack. Also
important to note is the syntactic differences. In order to create a variable 
named `FOO` in Forth you execute `VARIABLE FOO`, and in order to define a new
constant named `BAR` with value `23` you execute `23 CONSTANT BAR`. Obviously
these use parser words which Apællo has done away with. In order to revolve this
the syntax has been changed. In order to create a variable named `FOO` in Apællo
you execute `V$FOO`, and in order to define a new constant named `BAR` with the
value `23` you execute `23 C$BAR`. By switching to this syntax we do away with
the parser words, make it look more elegant, and make it more consise.

== Defining Words

Any language would be practically useless if it didn't allow you to definine
subroutines, functions, or procedures (save for a few esolangs). Obviously,
this can also be done in Forth, namely the syntax `: <word> <definition> ;`. In
traditional Forth fashion this was usually implemented _in Forth_ using parser
words. However, this is one of the _worst_ cases of their usage as it creates an
unreasonable amount of confusion and weirdness. The truth is, there is no reason
for it to be done this way. Apællo uses this same syntax, but because of its
lack of parser words it is implemented directly in the interpreter as part of
the core language. Another weird part of Forth is that when you redefine words,
the old definition is still kept, and the new one is simply added as a new entry
to the dictionary. Because of this, other words that referenced the redefined
word will continue to use the old one, creating situations in which rarely used
words can induce hard to find bugs by using old code, or requiring the developer
to redefine all the other words that use it as well so that they refer to the
updated dictionary entry. No other language works this way, and nor does Apællo.
In Apællo when you redefine words it modifies the previous entry so that all
references to it, whether created before or after the redefinition, will use the
newest version of the entry. You are allowed to define variables in words, as
well as constants, but these definitions are freed from the dictionary after the
word's execution, similar to a variable "going out of scope" in a mainstream
imperative language such as Java or C♯.

NOTE: Redefined words _change_ the entry instead of adding a new one, causing
      previously defined references to use the new version. This differs from
      Forth and can be a point of confusion to Forth programmers. Everyone is
      encouraged to read the above section carefully.

== Memory

Apællo's memory management works quite differently to memory management in the
traditional Forth. In Forth, you directly interact with the system's memory.
When you create a variable and attempt to access it, you get the address of the
variable's cell in the overall system memory, as if you converted a C pointer to
an integer. You also use the address of the target cell in the system's memory
to read/write to it. Furthermore, Forth doesn't have a native concept of complex
structures, so everything is organized into cells that can only contain numbers
(at least natively). In Apællo, memory works a lot different. It is organized
into lists, described earlier in this documentation, each of which is given a
unique "identifier" number. These contain things like list literals used in the
code, as well as variables and constants that are defined. These identifiers are
used in place of the system memory address in the original Forth. For example,
as described earlier, when you refer to a variable its identifier is given
instead of its memory address, and the same for the usage of lists.

=== Dictionaries

In the original Forth, when you create a new word it is stored in the designated
dictionary spot, among all other memory. They are directly accessible to the
code, and there is even a parser word, `'`, that gives you the address of the
desired word so you can do whatever with it. In Apællo, words are stored
separately to everything else, and are not directly accessible from the code.
This prevents weird situations such as developers manually defining functions, 
and self-modifying code. It also improves the security of the code by preventing
programmers from modifying words in ways that can mess with the interpreter or
attack exploits in the system, whether malicious or accidental. Overall it keeps
everything a lot cleaner and easier to reason about. Apællo has three different
dictionaries: the dictionary for executable words, the dictionary for variable,
and the dictionary for constants. As explained in the section on executing words
the interpreter, first the constants' dictionary is checked first, followed by
the variables' dictionary if it is not found, and finally the executable words'
dictionaries if it is still not found. Of course, if it is still not found then
an error is thrown to the user alerting them that the word is unknown.

=== Direct System Memory Accessing

While Apællo manages memory a lot differently than Forth and opts to use its own
identifier numbers instead of the system's memory addresses, you can still use
the system's memory addresses for interaction. However, cells of the system's
memory, when interacted with directly, can only contain numbers. Furthermore,
the interpreter makes no guarantee that the address will not cause system errors
such as segmentation faults or invalid memory addresses. Overall, the direct
usage of memory in Apællo is heavily discouraged as it is considered unsafe code
that requires quite the knowledge of the system to ensure that nothing is messed
up. There are legitamate uses to it however, such as writing to memory mapped
registers when running Apællo code on embedded chips. The interaction with the
memory is done in the same way as in the original Forth. In order to write to a
memory address you first push the new value to the stack, then you push the
target address to the stack, and finally you execute `!`. For example, in order
to set `FOO` to fifteen you write `15 FOO !`. In order to get the value of a
specific memory address you first push the target address ot the stack, and then
execute `@`. For example, in order to get the value of `FOO` you write `FOO @`.
There also exists the word `?`, which is defined as `@ .`, in order to make
interactive editing easier.